### ISSUE TITLE
Images left rather than center justified

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#25]
Images import from OpenStax aligned "left" in the original OpenStax text images were aligned "center"

requires some investigation into whether injecting html attributes is too prescriptive.

**Comment by bdolor** [comment]
The CSS for CNX books aligns images by default: 

![image](https://user-images.githubusercontent.com/2048170/31918348-0306b728-b811-11e7-950c-96fa7b3e34a5.png)

There is nothing in the HTML structure (such as inline styling) that would bring this style property over. Alignment of images is a theme choice. If it was desired it could be solved with custom CSS.

**Comment by lucwrite** [comment]
Hmm  I guess now that we have an ability to customize CSS that a style sheet would be better for this.

**Comment by lucwrite** [comment]
Validated
