### ISSUE TITLE
Remove Chapter Metadata from Import b/c PDF Export

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#26]
cnx_astro" appears in the table of contents under each chapter name
cc-by appears beside each chapter in the table of contents 

Bringing in the chapter metadata puts this data into the TOC in the PDF output. The more common use case is to transfer the burden of attribution to the author, rather than assuming it programmatically.

**Comment by bdolor** [comment]
@lucwrite - ready for validation

**Comment by lucwrite** [comment]
bdolor stupid question of the day - where can I find the screen that I can drag across an item when I have validated?

**Comment by bdolor** [comment]
2 places, projects tab at the top

![image](https://user-images.githubusercontent.com/2048170/31959240-019202b0-b8a9-11e7-8c36-fd4b342c943f.png)

or in the right nav of this page: 
![image](https://user-images.githubusercontent.com/2048170/31959282-1c6d93f6-b8a9-11e7-862f-61464b9e4b9d.png)

**Comment by lucwrite** [comment]
So I am doing testing and as part of this trying to export in all basic formats. I am in a meeting on Eduroam but export is failing on both https://pressbooksdev.bccampus.ca/openstaxchemtest and the Physics https://opentextbc.ca/openstaxphysicstest/. I imported Chem this morning and Physics yesterday. Is one of you able to test this and see if it related to my network or a new export error?

**Comment by bdolor** [comment]
What is the error message you're getting?

**Comment by lucwrite** [comment]
500

**Comment by bdolor** [comment]
It's throwing an error with the EPUB export. Doesn't like one or two of the images. Can you validate the issue without EPUB export?

**Comment by lucwrite** [comment]
Validated on Dev. 

-Chapter metadata still appears on https://pressbooks.bccampus.ca/ (assuming not implemented there yet. 

- Gettingexport error for PDF on https://opentextbc.ca/physicstestbook2/ so cannot test. Error code ue Oct 24 16:38:14 2017: error: failed to load all input documents
Tue Oct 24 16:38:14 2017: finished: failure
Tue Oct 24 16:38:14 2017: ---- end

**Comment by bdolor** [comment]
your assumption is correct — please don't test/validate on production servers.

**Comment by lucwrite** [comment]
Ok - sorry, I assumed an import test would be fine for testing as this plugin- Sorry about that - this is now validated.
