### ISSUE TITLE
OpenStax images in export for PDF are small

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#27]
Images appear smaller and left rather than center justified

**Comment by bdolor** [comment]
The images in OpenStax books are huge, generally. It looks like the images are being forced by the browser to appear smaller than they are naturally. In the example below, it's using a width property that's less than the original size of the image. 

![image](https://user-images.githubusercontent.com/2048170/31917825-7e97950e-b80e-11e7-84f1-a93f76bc9a92.png)

Removing the img attribute would let the image display at its natural dimensions. Is this what you're after (see below)?

![image](https://user-images.githubusercontent.com/2048170/31918181-30339b04-b810-11e7-9750-0d0495a57915.png)

**Comment by lucwrite** [comment]
No this is not what we are after. It would cause more issues than it would solve.

**Comment by bdolor** [comment]
is there anything left to do with this, or should we consider this resolved?

**Comment by lucwrite** [comment]
Resolve
