### ISSUE TITLE
bold not importing

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#28]
<b> not importing into from OpenStax into https://opentextbc.ca/

**Comment by bdolor** [comment]
@lucwrite — I need to able to test this, so that I can recreate the issue. Which CNX book and on what page is this a problem?

**Comment by lucwrite** [comment]
CNX https://cnx.org/contents/Ax2o07Ul@9.95:EC6WBNqn@7/Physical-Quantities-and-Units
OpenStax "We define a **Physical Quantity**"

Pressbooks Dev https://pressbooksdev.bccampus.ca/physicstestos/chapter/physical-quantities-and-units/   "We define a Physical Quantity"

I am guessing it is related to CSS

**Comment by bdolor** [comment]
it is...

![image](https://user-images.githubusercontent.com/2048170/32017078-868a9122-b97a-11e7-920a-bff9de635f4c.png)

I can put the style into the Open Textbook Theme, and of course, you can use Custom CSS

**Comment by bdolor** [comment]
this is done https://github.com/BCcampus/pressbooks-textbook/commit/ccceb90958519022dc5387a24a2e0f7604123294 

In order to see the changes on dev server, you may have to clear browser cache, switch themes to Luther and back again to Open Textbook

**Comment by lucwrite** [comment]
Tested and working. Moving over to done.
