### ISSUE TITLE
OpenStax Import Plugin - Equation Errors

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#29]
equations are no longer centred
large error message in Chapter 5.6 (Radiation and Spectra > The Doppler Effect) in "The Doppler Effect" textbosee attached image "astr.JPG") 
an equation missing a part: see screenshot <-- this is how the equation appears in Pressbooksdev <-- this is how the equation appears in the OpenStax book 
Equations missing symbols. For example in Δθ=Δsr. in OpenStax becomes in Pressbooks

original: 
https://cnx.org/contents/Ax2o07Ul@9.95:RCFtg_5-@7/Rotation-Angle-and-Angular-Vel

**Comment by bdolor** [comment]
@lucwrite — the equations not being centred is easy enough to target in custom CSS, and I've added the rule to the Open Textbook Theme: https://github.com/BCcampus/pressbooks-textbook/commit/a96c07e95e628dbf1695ed21f668ad2c149a0ad9

I can't recreate the Doppler error or the equations missing symbols. 

I imported those two chapters and below is how they look. If I'm not seeing something on those pages, please let me know: 

https://pressbooksdev.bccampus.ca/cnxphysics/chapter/rotation-angle-and-angular-velocity/
https://pressbooksdev.bccampus.ca/cnxphysics/chapter/doppler-effect-and-sonic-booms/

**Comment by lucwrite** [comment]
I cannot access, for some reason still do not seem to have super admin. Would you mind opening up so that I can access?

**Comment by bdolor** [comment]
you are a super admin.

**Comment by bdolor** [comment]
I can see it now — On this page, under Angular Velocity title I can see the Delta character `&#00394`:
https://cnx.org/contents/Ax2o07Ul@9.95:RCFtg_5-@7/Rotation-Angle-and-Angular-Vel
 
![image](https://user-images.githubusercontent.com/2048170/31967398-ad934aa6-b8c2-11e7-82dd-e4458bce859a.png)

for which there is a replacement rule https://github.com/BCcampus/pressbooks-openstax-import/blob/dev/inc/modules/import/openstax/xsl/entities.xsl#L26 

yet, it's getting stripped out.

**Comment by bdolor** [comment]
Eliminating this plugin as the source of the problem for Delta character &#x00394; not displaying. The MathML to LaTeX via XSL transformation correctly sends back Delta character. You can confirm this by looking at the source in the WYSIWYG: 

![image](https://user-images.githubusercontent.com/2048170/32075094-80d27192-ba50-11e7-96f7-b4d4e66819ca.png)

This offloads the problem to WP QuickLaTeX.
