### ISSUE TITLE
change the message to network activate the wp quick latex plugin. 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#30]
currently it asks users to network activate. This can cause problems for collections of books that were created using PB Latex shortcode.

**Comment by alexpflores** [comment]
Here's the existing messages. How can we improve them to avoid this problem? Should we leave it up to the book admin, and give them a warning there about enabling this when using PB Latex shortcodes? 

**Network Admin message:** 
"Please network activate WP QuickLaTeX for multiline equations and svg image export support" 

**Book Admin message:** 
"Your Network Administrator has made WP QuickLaTeX ailable to you from your plugins menu. Please activate it to enable multiline equations, and svg image export support."

**Comment by bdolor** [comment]
I would propose removing encouraging anyone to network activate it.

**Comment by bdolor** [comment]
@lucwrite no way for you to validate this, since the admin notice goes away if you dismiss it once. Moving to Done.
