### ISSUE TITLE
ensure compatibility with latest PB

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#31]
Updating OpenStax Import Plugin requires testing it on the latest version of: 

- PB
- PBT
- PB Book theme
- PB Publisher
- WP

**Comment by bdolor** [comment]
pressbooksdev.bccampus.ca and opentextbcdev now have the latest of: 

- PB
- PBT
- PB Book Theme
- PB Publisher
- WP

**Comment by bdolor** [comment]
On Friday morning, Oct. 27 the production server will be upgraded to all the latest to match the dev server. @lucwrite will you send out your communication piece after it has been upgraded?

**Comment by lucwrite** [comment]
Yes I will be sending this to help desk to send out more broadly.

**Comment by bdolor** [comment]
PB and PB Book Theme just came out with a new release this morning. Will apply changes to the dev server.

https://github.com/pressbooks/pressbooks-book/releases/tag/1.10.5
https://github.com/pressbooks/pressbooks/releases/tag/4.3.5

**Comment by bdolor** [comment]
PB Book v1.10.5 and PB v4.3.5 applied to dev server

**Comment by bdolor** [comment]
Production server is now up to date - @lucwrite ok to test and verify

**Comment by lucwrite** [comment]
Validated https://opentextbc.ca/

**Comment by lucwrite** [comment]
Validated all changes on https://pressbooks.bccampus.ca

Question: Do I need to move each of the items into the live channel now

**Comment by bdolor** [comment]
Thanks @lucwrite — I can do that.

**Comment by lucwrite** [comment]
Laurie was under the impression that this plugin was intended to for 'internal use" and we did not need to communicate these changes to all our community users. Do you know?

**Comment by bdolor** [comment]
This plugin was released publicly and committed to the wordpress.org repository in August and announced generally to the organization in Rocket Chat channel. 

https://wordpress.org/plugins/presbooks-openstax-import/

**Comment by lucwrite** [comment]
Thanks let me know when we are ready to send the communication out through the help desk.

**Comment by bdolor** [comment]
The development piece was complete this morning and if you've validated, then it's all in your court.
