### ISSUE TITLE
pressbooksdev server open to the outside world

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#32]
### Description 

Certification server is currently open to the world presenting a large attack surface, especially with over 140 user accounts. This can be mitigated by locking down access to BCcampus IP addresses as is the case already with other certification servers. Users of the site would access the servers via VPN or by being in either one of the offices.

**Expected behaviour** 

I would expect servers that we are working on for internal purposes are available only to our internal network. 

**Actual behaviour** 

It's exposed to the world.

**Comment by bdolor** [comment]
I've enabled IP rules that will restrict access to the dev/cert server on our internal network, or via VPN. @alexpflores can you verify?

**Comment by alexpflores** [comment]
@bdolor Verified. I cannot access server when not on VPN, working as expected.

**Comment by bdolor** [comment]
🏖
