### ISSUE TITLE
Inclusion of Preface, Appendix for College Physics

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#37]
### Description 

College Physics has Appendix pages and Preface pages that are not included on import. 

**Expected behaviour** 

All pages come in

**Actual behaviour** 

Exclusion.

### Steps to reproduce the problem

Import https://cnx.org/contents/Ax2o07Ul@9.95:pFeekPiU@17/Preface and look for Glossary, Preface, Atomic Masses, Selected Radioactive Isotopes

**Comment by bdolor** [comment]
@lucwrite - ready for validation

**Comment by lucwrite** [comment]
Successfully tested in Dev -- Appendix and front matter appear.
