### ISSUE TITLE
Swap [link] for (Figure)

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#38]
### Description 

arbitrary value of `[link]` is given to all links to Figures. It would be more descriptive if it could be changed to `(Figure)`

**Expected behaviour** 

links to Figures would be labelled semantically

**Actual behaviour** 

labelling is vague and unhelpful

### Steps to reproduce the problem

Import any book with anchor links to Figures

**Comment by bdolor** [comment]
@lucwrite - ready for validation

**Comment by lucwrite** [comment]
Tested successfully in PB Dev
