### ISSUE TITLE
[10-Nov-2017 16:39:37 UTC] \Pressbooks\Modules\Import::formSubmit html import error, wp_remote_head()cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by medic917** [BCcampus/pressbooks-openstax-import#42]
### Description 
I'm getting timeout error as shown below.

[10-Nov-2017 16:39:37 UTC] \Pressbooks\Modules\Import::formSubmit html import error, wp_remote_head()cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received
It sometimes gives me HTTP 500 error.

I have my .htaccess settings to 
php_value upload_max_filesize 192M
php_value post_max_size 192M
php_value max_execution_time 1000
php_value max_input_time 1000

So I don't know why it's timing out.
I'm using this book: https://cnx.org/exports/9b08c294-057f-4201-9f48-5d6ad992740d@5.57.zip/college-algebra-5.57.zip
# Any way we can upload zip file into my server and import locally?

**Expected behaviour** 

Should import.

**Actual behaviour** 

Should import, but it loads, hangs, and eventually gives me the mentioned error above. It also sometimes gives me HTTP 500 error.

### Steps to reproduce the problem

I'm using Ubuntu 16.04, I have pressbooks fully installed with themes and plugins.
Using this url book https://cnx.org/exports/9b08c294-057f-4201-9f48-5d6ad992740d@5.57.zip/college-algebra-5.57.zip

### System Information

- Pressbooks OpenStax Import: 0.1.3
- Pressbooks:  4.3.5
- WordPress: 4.8.3

**Comment by bdolor** [comment]
@medic917 thank you — though I can't recreate the 500 error or the hanging/timeout with that college algebra textbook I can tell you that a 500 error or timeout from a `wp_remote_head()`/`curl` request indicates an  issue with the receiving end of the request (cnx.org) and not the plugin. I can only advise that you try again? I had no problem importing that textbook only moments ago. 

To answer if you can upload a zip file to your server and import locally, I would say that wouldn't be possible. Uploading (huge) zip files to servers has the potential to invite all sorts of trouble which informed the alternative approach we took. 

Thank you for the detailed report, it's appreciated.

**Comment by bdolor** [comment]
closing for now.
