### ISSUE TITLE
WPINC is not defined. Plugin causes white screen.

### ISSUE THREAD

**Issue by connerbw** [BCcampus/pressbooks-openstax-import#44]
### Description 

Installing `pressbooks-openstax-import` using composer causes a white screen. The bug is in `collizo4sky/persist-admin-notices-dismissal`. More info:

https://github.com/collizo4sky/persist-admin-notices-dismissal/issues/14

**Expected behaviour** 

WordPress site loads.

**Actual behaviour** 

White screen.

### System Information

- Pressbooks OpenStax Import: 0.1.3
- Pressbooks: dev
- WordPress: 4.9.1

**Comment by connerbw** [comment]
Fixed in `collizo4sky/persist-admin-notices-dismissal` :

https://github.com/collizo4sky/persist-admin-notices-dismissal/issues/14#issuecomment-359662694

**Comment by alexpflores** [comment]
Thanks @connerbw
