### ISSUE TITLE
Changes to `pb_initialize_import` in next version of Pressbooks

### ISSUE THREAD

**Issue by connerbw** [BCcampus/pressbooks-openstax-import#45]
### Description 

We've made changes to the `pb_initialize_import` filter. The old one was buggy. It only let one 3rd party importer, the last loaded, work at time. It would override all the others. Old code:

`$importer = apply_filters( 'pb_initialize_import', null );`

New code:
 > https://github.com/pressbooks/pressbooks/blob/3fe31d85b46b46b6da8df7229716e50f55b6f776/inc/modules/import/class-import.php#L312

As you can hopefully see from the new code, we've done it in way that if you only have one extra importer on your PB install, everything will work the way it did before. We're essentially supporting broken behaviour to minimize impact on existing installs. 

_Right now, as I type, any PB with more than one 3rd party importer is broken._

My request is that when PB5 is released, please change your code to:

```
/**
 * Inserts our OpenStax Class into the mix
 *
 * @param array $a
 * @return OpenStax\Cnx[]
 */
function poi_add_initialize_import( $a ) {
    $a[] = new OpenStax\Cnx();
    return $a;
}

// ...

class Cnx extends Import {
    CONST TYPE_OF = 'zip';
    // ...
}
```

Thanks.

### System Information

- Pressbooks OpenStax Import: 0.1.3
- Pressbooks: 5.0.0 (or dev branch)
- WordPress: 4.9.2

**Comment by bdolor** [comment]
thank you @connerbw - will do

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-openstax-import/pull/47
