### ISSUE TITLE
notifications at the time of import

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#54]
for contextual learning, or just in time learning, add meaningful notification messages at the time of import that: 

- ask if wp-quicklatex is activated (depending on whether the book they are importing has equations) 
- rendering issues with wp-quicklatex for the first page load will be slower than usual (for image caching)
- some messaging around large file sizes my take a long time.

**Comment by bdolor** [comment]
doing this in stages... @lucwrite I've done a quick drive-by of one of the three notifications mentioned above via https://github.com/BCcampus/pressbooks-openstax-import/commit/99838e1dc10553f1c7b7792e06e1f3fd2aaab1b4. can be modified, depending on the outcome of #57

**Comment by lucwrite** [comment]
Looks good - A suggestion Importing a book with Latex equations activate...

**Comment by bdolor** [comment]
addressed in https://github.com/BCcampus/pressbooks-openstax-import/commit/756f2b3a4789b7c3dbc0e5761077c5a47d3754b7

## messaging when wp-quicklatex is *not* activated:

![image](https://user-images.githubusercontent.com/2048170/39886964-d89b85fa-5445-11e8-8c00-6269d907d409.png)


## messaging when wp quicklatex *is* activated: 

![image](https://user-images.githubusercontent.com/2048170/39886866-9a08e918-5445-11e8-8a8d-0b19e8990e92.png)
