### ISSUE TITLE
attributions evaluation

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-openstax-import#58]
evaluate the work already done to incorporate candela attributions plugin to determine if this is a good place to start or if something else needs to be built. 

https://github.com/BCcampus/pressbooks-textbook/pull/121

**Comment by lucwrite** [comment]
Currently, we are unable to get Candella attributions to display so this evaluation is based on how attributions show up on Lumen Candella. If we were are able use this tool according to @josieg would need to a) be able to reorder attributions b) delete attributions c) have figure numbers so which image or item is attributed is known. d) A smaller box for attributions so they do not take up to much space - as this would not work very well multiple attributions. (minimal viable)

@josieg says ideal = "I don't know how feasible this is, but ideally I'd like the attribution tool to work like the footnote feature in Pressbooks. A user could select an attribution icon from the top menu which would open an attribution builder, they would then input all info for that attribution and save it, which would generate an attribution statement that would appear at the end of the chapter (like footnotes do) but numbered and grouped separately from the footnotes."

**Comment by bdolor** [comment]
@lucwrite can you provide a link to the book where you are doing this evaluation?

**Comment by lucwrite** [comment]
Josie was referring to original ticket and what she thinks are basic requirements for tool.

**Comment by lucwrite** [comment]
Was able to do more testing overall this seems like a  functional tool for the community if several elements can be changed. I was able to reorder attributions and collapse them for more space when creating. The first one of the list is critical if we will have authors use.  The remainder are important:

1. Critical: Export PDF attribution size is too large in terms of space it takes up. See attached screenshot. Each attribution needs to be on a single line with no indented bullet point section with a small amount of space between attributions. Appearance should be similar to current footnote format but numbered and grouped separately from footnotes.  The attributions could be set to appear either under the content or like endnotes at the end of the chapter in the PDF export. 

2. Important: - From the ticket issued by @josieg 
A. The "Type" drop down menu isn't useful. I'd rather the attributions be sorted alphabetically by figure number than by license type. As such, the "Type" option could be replaced by a textbox, where the person could write the number associated with the image/table, etc(Example: Figure 4.3 or Table 1.2). That would be used to sort the attributions.
B. "Description" would be better titled "Title/Description"
C. "Author" would be better titled "Author/Copyright holder"
the "URL" box would be better titled "Link to original source" - or something like that
D. I think the "license terms" box would be better titled "More information," and then it could be used for anything extra
E. There needs to be a place to put the second url in case the photographer has a flikr page or something like that, it could be called "Link to author's page"
D. The tab where you see the attributions in the live book should be titled "Attributions," not "Citations"
E. The author can delete attributions

![image](https://user-images.githubusercontent.com/19966949/39935645-93c3e15c-54fe-11e8-8e43-fdd5ce2d59f1.png)

**Comment by bdolor** [comment]
closing, superseded by work done on media attributions feature submitted back to PB
