### ISSUE TITLE
Importing throws PHP notice

### ISSUE THREAD

**Issue by greatislander** [BCcampus/pressbooks-openstax-import#64]
### Description 

Importing an OpenStax file with WP_DEBUG enabled reveals a PHP notice during the import routine:

```
Notice: Undefined variable: organizations in pressbooks-openstax-import/inc/import/openstax/class-cnx.php on line 308
```

https://github.com/BCcampus/pressbooks-openstax-import/blob/dev/inc/import/openstax/class-cnx.php#L308.

**Expected behaviour** 

No PHP notices.

**Actual behaviour** 

Undefined variable.

### Steps to reproduce the problem

Import this file: https://cnx.org/exports/9add9912-c6a7-49a5-8c75-cca4187fdb57@1.1.zip/bitcoin-1.1.zip

<img width="1221" alt="screen shot 2018-06-28 at 2 47 45 pm" src="https://user-images.githubusercontent.com/605361/42051443-782721e8-7ae2-11e8-85ac-0ee1660ca840.png">

### System Information

- Openstax Import for Pressbooks: 1.2.2 
- Pressbooks: 5.4.0-dev 
- WordPress: 4.9.6

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-openstax-import/commit/9e45a40038d6deba9f74cd8ac305507a932521cb
