### ISSUE TITLE
Embedded videos are stripped during import

### ISSUE THREAD

**Issue by greatislander** [BCcampus/pressbooks-openstax-import#67]
### Description 

Related to much previous discussion, it appears that embedded YouTube videos (in iframes) are stripped during the import routine.

**Expected behaviour** 

They should remain, ideally as OEmbeds?

**Actual behaviour** 

The container `<div>` remains but the video is gone.

### Steps to reproduce the problem

Import this book: https://cnx.org/contents/mt2ZEsan@1.1:E1v-20BP@1/Introduction-to-Bitcoin

Look for videos in the Introduction. They're gone.

### System Information

- Openstax Import for Pressbooks: 1.2.2
- Pressbooks: 5.4.0-dev
- WordPress: 4.9.6

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-openstax-import/commit/9314af97761a1528fe2f7669721637b49b5e57e6
