### ISSUE TITLE
Image Not importing from cnx to pressbooks

### ISSUE THREAD

**Issue by johnpeterm** [BCcampus/pressbooks-openstax-import#72]
### Description 

When importing  book from zip file the  images does not get imported
![11](https://user-images.githubusercontent.com/20897821/42823684-c608d69a-89fb-11e8-9ca3-c86eb2868097.png)

**Expected behaviour** 

[What you expected to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[
**First Step,**
Download the zip file from cnx

**Second Step,**
Import the file into pressbooks
Check images
]

### System Information

- Openstax Import for Pressbooks: [Enter POI Version here] 
- Pressbooks: [Version 5.4.0] 
- WordPress: [Version 4.9.7]

**Comment by bdolor** [comment]
thanks for the report @johnpeterm - will take a look

**Comment by bdolor** [comment]
sorry @johnpeterm - I can't reproduce this one. The image on that book imports for me: 

![image](https://user-images.githubusercontent.com/2048170/43669409-981ce0ac-9737-11e8-87df-c1e99a3402f3.png)
