### ISSUE TITLE
Import Error: Destination directory for file streaming does not exist or is not writable

### ISSUE THREAD

**Issue by johnpeterm** [BCcampus/pressbooks-openstax-import#74]
### Description 

When importing  Book from the URL : https://cnx.org/contents/HLT_qvJK@6.2:wsOQ6HtH@8/Preface-to-Pfeiffer-Applied-Pr

We get the error 
Destination directory for file streaming does not exist or is not writable
![14](https://user-images.githubusercontent.com/20897821/42832177-09e7ffd2-8a0e-11e8-8eba-0b711392a04a.png)

**Expected behaviour** 

[What you expected to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

Import book from URL: https://cnx.org/contents/HLT_qvJK@6.2:wsOQ6HtH@8/Preface-to-Pfeiffer-Applied-Pr

### System Information

- Openstax Import for Pressbooks: [Enter POI Version here] 
Pressbooks: [Version 5.4.0]
WordPress: [Version 4.9.7]

**Comment by bdolor** [comment]
Hi @johnpeterm - the value of the URL seems to be problematic. If you're using the URL to import an openstax book, it's meant to point at the downloadable zip file. So for the above book, that URL would be: 
- https://cnx.org/exports/1cb4ffaa-f24a-4b98-8e03-5dd217011f0c@6.2.zip/applied-probability-6.2.zip 

If you use the above URL, the book imports without any problems. 

![image](https://user-images.githubusercontent.com/2048170/43668843-f1b8b22a-9733-11e8-8744-85b7f84b992d.png)

The value you've supplied above only points to the preface page. The importer isn't designed to bring in individual pages, rather the entire openstax book.

**Comment by johnpeterm** [comment]
The cause of the above error seems to be an server issue. Temporary files were not allowed to created, once we allowed temp files to be created in the server, the book imported perfectly fine.

**Comment by bdolor** [comment]
great! good to know, thanks for following up.
