### ISSUE TITLE
Plugin slug on WordPress.org has a typo

### ISSUE THREAD

**Issue by greatislander** [BCcampus/pressbooks-openstax-import#75]
### Description 

https://wordpress.org/plugins/presbooks-openstax-import/ (only one 's' in Pressbooks)

**Expected behaviour** 

Slug matches GitHub repo name.

**Actual behaviour** 

Slug doesn't match GitHub repo name.

### Steps to reproduce the problem

Not applicable.

### System Information

- Openstax Import for Pressbooks: 1.2.4

**Comment by bdolor** [comment]
I've been ignoring the typo for too long...agreed, it needs to be addressed.

**Comment by greatislander** [comment]
I hadn't noticed because I installed from GitHub and then I wasn't sure why the 1.2.4 update wasn't showing up 🙃

**Comment by bdolor** [comment]
I've requested a change, though the language in their policy doesn't appear to leave much wiggle room: https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#can-i-change-my-plugins-urlslug 

Will look at what my options are after I hear back from them. I floated closing down the misspelled repo and submitting/opening another one with correct spelling.

**Comment by bdolor** [comment]
The wordpress folks have closed the misspelled repo and I've re-submitted a new one with the correct spelling.

**Comment by bdolor** [comment]
resolved https://wordpress.org/plugins/pressbooks-openstax-import/
