### ISSUE TITLE
No images after import

### ISSUE THREAD

**Issue by otterscotter** [BCcampus/pressbooks-openstax-import#76]
### Description 

I've imported Principles of Economics 2e via offline zip and none of the images came over. Is this a simple size issue?

**Expected behaviour** 

I expected images to import. Expected the picture of phone to appear inline with text (see image below).
https://cnx.org/contents/vEmOH-_p@6.4:3ZlSW1C7@6/Introduction

![sketch 52](https://user-images.githubusercontent.com/37352212/46179359-9ca4bb00-c26f-11e8-9054-964f07583e48.png)

**Actual behaviour** 

No inline images. See image below with only text and broken image icon.
[https://pbooks.scottrobison.net/prinecon2/chapter/introduction/](https://pbooks.scottrobison.net/prinecon2/chapter/introduction/)

![sketch 50](https://user-images.githubusercontent.com/37352212/46179191-f8bb0f80-c26e-11e8-8a61-9e0d893970c4.png)

### Steps to reproduce the problem

Import Principles of Econ 2e (via offline zip).
[https://cnx.org/contents/vEmOH-_p@5.1:3ZlSW1C7@3/Introduction](https://cnx.org/contents/vEmOH-_p@5.1:3ZlSW1C7@3/Introduction)

### System Information

- Openstax Import for Pressbooks: 1.2.4
- Pressbooks: 5.5.1
- WordPress: 4.9.8

**Comment by bdolor** [comment]
Your first GitHub issue @otterscotter - Hooray! Will take a look, thanks for reporting.

**Comment by otterscotter** [comment]
Same problem with the OpenStax Psychology book. No images imported.
Figure caption displays as normal text, then broken image icon, then picture's alt text.
Here is the link to the Offline Zip:
https://cnx.org/exports/4abf04bf-93a0-45c3-9cbc-2cefd46e68cc@9.2.zip/psychology-9.2.zip

![sketch 56](https://user-images.githubusercontent.com/37352212/46628425-5dd5f700-caf2-11e8-9e19-f026dce8855e.png)

**Comment by otterscotter** [comment]
I've also tried importing just section #2 "What is Psychology" from OpenStax Psychology text and no images are imported.

**Comment by bdolor** [comment]
Cannot reproduce, sorry. I imported both books successfully. Images are coming through as expected. For troubleshooting, I'd look to error logs/messages of any kind. 

_Psychology_
![image](https://user-images.githubusercontent.com/2048170/46635159-3e49c900-cb08-11e8-973c-31837f8ce255.png)

_What is Psychology_
![image](https://user-images.githubusercontent.com/2048170/46635207-62a5a580-cb08-11e8-844e-eb2b5c14d553.png)

_Principles of Economics_
![image](https://user-images.githubusercontent.com/2048170/46635419-35a5c280-cb09-11e8-9679-ba3adbe8148c.png)

**Comment by otterscotter** [comment]
Good to know! 
I'm not getting any error messages. Are there other logs in PB I could check? Any insight is appreciated. 
And thanks for testing!

**Comment by bdolor** [comment]
if your server logs aren't producing anything meaningful you can configure WP application to produce debug error messages in a log file — Good place to start: https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging
