### ISSUE TITLE
Images with spaces in file name are not imported

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-openstax-import#77]
### Description 

When importing an OpenStax book using the openstax import plugin, images that have spaces in their file names are not imported. 

**Expected behaviour** 

All images should import. 

**Actual behaviour** 

Images with spaces in their file name are not imported. 

### Steps to reproduce the problem

1. import Introduction to Business: OpenStax (https://openstax.org/details/books/introduction-business) into Pressbooks. 
2. See an example of a missing image in this chapter: https://pressbooksdev.bccampus.ca/testingopenstax/chapter/the-nature-of-business/

![space](https://user-images.githubusercontent.com/23706762/47110837-c023ab80-d206-11e8-8e26-77ea58b2918f.JPG)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-openstax-import/commit/e57a4b342a557ba33bd8361d4c0eed555a4ed3e7

**Comment by josieg** [comment]
Just tested, looks good!
