### ISSUE TITLE
Textboxes stripped out during import

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-openstax-import#80]
### Description 

Content that is in textboxes in CNX does not appear in textboxes in Pressbooks. Instead, that content appears as plain text, and doesn't even have a proper heading. 

**Expected behaviour** 
I expect that text that is in textboxes in CNX will also appear in textboxes when the content is imported into Pressbooks. And I expect that headers in those textboxes will be given a heading level in Pressbooks.

**Actual behaviour** 

Instead, text that was in textboxes in CNX appears as plain text in Pressbooks with the heading no longer marked as a heading.

For example, see section titled "INDIVIDUAL-SOCIETY CONNECTIONS" on each page: 

- [What is Sociology (OpenStax)](https://cnx.org/contents/AgQDEnLI@11.1:XZe6d2Jr@11/What-Is-Sociology)
- [What is Sociology (Pressbooks copy)](https://pressbooks.bccampus.ca/testingopenstaxtake2/chapter/what-is-sociology/)

**Comment by josieg** [comment]
In a new OpenStax publication ([Business Ethics](https://cnx.org/contents/kUrGbuHs@3.1:FsaaJM1v@3/1-1-Being-a-Professional-of-Integrity#44598)), not only is the textbox removed, by the main heading of the textbox is removed too when importing into Pressbooks. See the following:
**CNX view:**
![openstaxtextbox](https://user-images.githubusercontent.com/23706762/48287268-2a51f980-e41d-11e8-8816-95f96f7631a5.JPG)
**Pressbooks view**
![openstaxtextbox1](https://user-images.githubusercontent.com/23706762/48287269-2a51f980-e41d-11e8-9da4-ddaa98581f10.JPG)

**Comment by bdolor** [comment]
@josieg - the content on the web `Ethics Across Time and Cultures`, simply isn't there in the zip file. Lends weight to a migration to the API. 

![image](https://user-images.githubusercontent.com/2048170/48800249-1b413600-ecbe-11e8-8874-eeb852527a2e.png)

**Comment by bdolor** [comment]
the formatting part of this resolved via https://github.com/BCcampus/pressbooks-textbook/commit/2a088c641d9c84e2daf164dc1de4e52fc3e3d42a

**Comment by josieg** [comment]
That's annoying re: headings not being in the xml. But your formatting fix looks good.
