### ISSUE TITLE
Footnotes: Note text appears at the bottom of the page with no indication of where it is referencing

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-openstax-import#83]
## Description

Footnotes are not importing properly. The **note reference mark** (aka the superscript number that marks the spot of a citation in a paragraph) is stripped out during import and a space is inserted where it should be. The **note text** (e.g the actual citation statement that the note reference mark is pointing to) appears at the bottom of the page in an ordered list above the glossary terms. 

### Expected behaviour

I expect that when importing an OpenStax book into Pressbooks, end notes in the CNX platform would be pulled into the Pressbooks footnote tool. This would involve putting the note text from the CNX platform into `[footnote]x[/footnote]` tags where the note reference mark was.

This would insure that:

- note reference marks would mark the spot in a paragraph to match the source
- that note reference marks would appear as superscript numbers that appear in the order that they appear on the page, 
- that note text would have numbers matching their note reference marks, and 
- that behaviour of footnotes could be controlled in Theme Options and CSS.

### Actual behaviour
**Here a paragraph with a note reference mark in the CNX platform.**
![cnxfootnote](https://user-images.githubusercontent.com/23706762/48425988-bc5a4a80-e71a-11e8-8d40-829f52a80e93.JPG)
**Here is the same paragraph after it has been imported into Pressbooks:**
![cnxpbfootnote](https://user-images.githubusercontent.com/23706762/48426091-ef044300-e71a-11e8-89fd-760701722567.JPG)
Note the following:

- a space has been inserted within the paragraph
- the note reference mark has disappeared

**Here is what the same paragraph looks like in the html editor in Pressbooks:**
![cnxpbhtmlfootnote](https://user-images.githubusercontent.com/23706762/48426352-78b41080-e71b-11e8-8606-036656db7e0c.JPG)

And here is what the note text looks like once it's been imported into Pressbooks:
![cnxpbendnote](https://user-images.githubusercontent.com/23706762/48427813-7901db00-e71e-11e8-852f-bfc78d960bc2.JPG)

### Steps to reproduce the problem

1. Import a book into Pressbooks that has footnotes. E.g., [Business Ethics](https://cnx.org/contents/kUrGbuHs@3.2:6KQQIO6W@3/1-2-Ethics-and-Profitability)
2. Look at the places where footnotes should be in the Pressbooks version. (Here is a [PB copy of Business Ethics](https://opentextbc.ca/businessethicsopenstax/chapter/ethics-and-profitability/))

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-openstax-import/commit/afec817cd9307a80e04444b5a6e35336f147ee89

**Comment by josieg** [comment]
This fix also looks good.
